apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d7f0igwg4-python
  janus-idp.io/tekton: d7f0igwg4-python
  backstage.io/kubernetes-id: d7f0igwg4-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: d7f0igwg4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
