apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d7f0igwg4-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d7f0igwg4-python 
  name: d7f0igwg4-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d7f0igwg4-python 
