apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d7f0igwg4-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:7e6ccecdc25893a31af7be9185e2eec8e5f122e3@sha256:4c81b7c2297c75800d716fdcdc80bb73bc3955ad9b9d62d4bb0562fe7693d667
          name: container-image
